"""
This script is an example inferencing system that uses cgm.py
and provides a simple chat interface in website form. This version
can display plots generated by the agent.

This script must be run with streamlit instead of python directly.
"""

from typing import Dict, Any, List

import streamlit as st
import torch
import gc
import traceback
import re
import os

iposter_url = "https://agu24.ipostersessions.com/default.aspx?s=29-F5-8A-FE-5F-2A-DB-76-CD-96-D6-C2-68-56-52-3D&guestview=true"

if "chat_history" not in st.session_state:
    st.session_state.chat_history = []

if "message_counter" not in st.session_state:
    st.session_state.message_counter = 0

torch.classes.__path__ = []

@st.cache_resource
def setup_engine():
    """Setup the ChatGeo-Magi engine with caching"""
    try:
        from cgm import ChatGeoMagi
        from config import SystemConfig
        
        config = SystemConfig()
        llm, embeddings, retriever = ChatGeoMagi.get_shared_resources(config)
        cgm = ChatGeoMagi(config)
        
        return llm, embeddings, retriever, cgm
    except Exception as e:
        st.error(f"Failed to setup engine: {str(e)}")
        st.stop()

def format_text_with_think_tags(text: str) -> str:
    """Format text to handle <think>...</think> spans even with multiline indentation safely in Streamlit."""
    pattern = re.compile(r'<think>(.*?)</think>', flags=re.DOTALL)

    def replace(match):
        content = match.group(1).strip()
        content = re.sub(r'\n\s*', '<br>', content)
        return f'<div style="font-size: 0.9em; color: #888888; font-style: italic; margin-bottom: 0.5em;">{content}</div>'

    return pattern.sub(replace, text.strip())

def parse_agent_step(step_data: Dict[Any, Any], step_index: int = 0, previous_was_tool_call: bool = False) -> Dict[str, Any]:
    """Parse agent step data for display with improved categorization"""
    parsed = {
        "step_type": "unknown",
        "content": "",
        "tool_calls": [],
        "observations": [],
        "reasoning": ""
    }

    print(step_data)
    
    try:
        messages = step_data.get("messages", [])
        if not messages:
            return parsed
        
        last_message = messages[-1]
        
        if hasattr(last_message, 'content'):
            content = last_message.content
            
            if hasattr(last_message, 'tool_calls') and last_message.tool_calls:
                parsed["step_type"] = "tool_call"
                parsed["tool_calls"] = [
                    {
                        "name": tool_call.get("name", "Unknown"),
                        "args": tool_call.get("args", {}),
                        "id": tool_call.get("id", "")
                    }
                    for tool_call in last_message.tool_calls
                ]
                parsed["content"] = content
                
            elif previous_was_tool_call:
                parsed["step_type"] = "tool_result"
                parsed["content"] = content
                parsed["observations"].append(content)
                
            elif step_index == 0 and content and not content.strip().startswith('<think>'):
                parsed["step_type"] = "user_query"
                parsed["content"] = content
                
            elif content and ('<think>' in content):
                parsed["step_type"] = "reasoning"
                parsed["content"] = content
                parsed["reasoning"] = content
            else:
                parsed["step_type"] = "reasoning"
                parsed["content"] = content
                parsed["reasoning"] = content
                
        else:
            parsed["content"] = str(last_message)
            parsed["step_type"] = "unknown"
        
    except Exception as e:
        parsed["content"] = f"Error parsing step: {str(e)}"
        parsed["step_type"] = "error"
    
    return parsed

def display_agent_step(step_data: Dict[str, Any], step_number: int):
    """Display an individual agent step in an expandable format with improved categorization"""
    step_type = step_data["step_type"]
    
    if step_type == "user_query":
        return
    
    if step_type == "tool_call":
        emoji = "🔧"
        title = f"Tool Call {step_number}"
    elif step_type == "tool_result":
        emoji = "📊"
        title = f"Tool Result {step_number}"
    elif step_type == "reasoning":
        emoji = "🧠"
        title = f"Reasoning {step_number}"
    elif step_type == "error":
        emoji = "❌"
        title = f"Error {step_number}"
    else:
        emoji = "❓"
        title = f"Step {step_number}"
    
    with st.expander(f"{emoji} {title}", expanded=False):
        if step_type == "tool_call" and step_data["tool_calls"]:
            for tool_call in step_data["tool_calls"]:
                st.markdown(f"**Tool:** `{tool_call['name']}`")
                if tool_call["args"]:
                    st.markdown("**Arguments:**")
                    st.json(tool_call["args"])
            
            if step_data["content"] and '<think>' in step_data["content"]:
                st.markdown("**Reasoning:**")
                formatted_content = format_text_with_think_tags(step_data["content"])
                st.markdown(formatted_content, unsafe_allow_html=True)
        
        elif step_type == "tool_result":
            st.markdown("**Result:**")
            st.code(step_data["content"], language="text")
        
        elif step_type == "reasoning":
            st.markdown("**Reasoning:**")
            formatted_content = format_text_with_think_tags(step_data["content"])
            st.markdown(formatted_content, unsafe_allow_html=True)
        
        elif step_type == "error":
            st.markdown("**Error:**")
            st.error(step_data["content"])
        
        else:
            st.markdown("**Content:**")
            st.text(step_data["content"])

def display_chat_message(message: Dict[str, Any], is_user: bool = False):
    """Display a single chat message with proper formatting"""
    if is_user:
        with st.chat_message("user"):
            st.markdown(message["content"])
    else:
        if "final_response" in message:
            formatted_response = format_text_with_think_tags(message["final_response"])
            st.markdown(formatted_response, unsafe_allow_html=True)
        
        if "agent_steps" in message and message["agent_steps"]:
            display_steps = [step for step in message["agent_steps"] if step["step_type"] != "user_query"]
            
            if display_steps:
                st.markdown("---")
                st.markdown("**Agent Reasoning Process:**")
                
                for i, step in enumerate(display_steps, 1):
                    display_agent_step(step, i)
        
        if "plots" in message and message["plots"]:
            st.markdown("---")
            st.markdown("**Generated Plots:**")
            for plot in message["plots"]:
                if plot.get("type") == "image":
                    st.image(plot["data"], caption=plot.get("caption", "Generated Plot"))
                elif plot.get("type") == "plotly":
                    st.plotly_chart(plot["data"])

def process_agent_response(agent_response) -> Dict[str, Any]:
    """Process the agent response and extract steps and final answer"""
    processed = {
        "final_response": "",
        "agent_steps": [],
        "plots": []
    }
    
    try:
        if hasattr(agent_response, '__iter__'):
            steps = []
            for i, step in enumerate(agent_response):
                steps.append(step)
                previous_step = processed["agent_steps"][-1] if processed["agent_steps"] else None
                previous_was_tool_call = previous_step and previous_step["step_type"] == "tool_call"
                
                parsed_step = parse_agent_step(step, step_index=i, previous_was_tool_call=previous_was_tool_call)
                content = parsed_step["content"]

                if (
                    parsed_step["step_type"] == "tool_result" and
                    isinstance(content, str) and
                    content.endswith(".png") and
                    os.path.exists(content)
                ):
                    processed["plots"].append({
                        "type": "image",
                        "data": content,
                        "caption": f"Generated Plot (step {i+1})"
                    })

                if parsed_step["step_type"] != "unknown":
                    processed["agent_steps"].append(parsed_step)
            
            if steps:
                last_step = steps[-1]
                messages = last_step.get("messages", [])
                if messages:    
                    final_message = messages[-1]
                    if hasattr(final_message, 'content'):
                        processed["final_response"] = final_message.content
                    else:
                        processed["final_response"] = str(final_message)
        
        else:
            messages = agent_response.get("messages", [])
            if messages:
                final_message = messages[-1]
                if hasattr(final_message, 'content'):
                    processed["final_response"] = final_message.content
                else:
                    processed["final_response"] = str(final_message)
    
    except Exception as e:
        processed["final_response"] = f"Error processing response: {str(e)}"
        processed["agent_steps"] = [{
            "step_type": "error",
            "content": traceback.format_exc(),
            "tool_calls": [],
            "observations": [],
            "reasoning": ""
        }]
    
    return processed

def main():
    st.set_page_config(
        page_title="ChatGeo-Magi Demo", 
        page_icon="🧲",
        layout="wide"
    )
    
    st.title("🧲 ChatGeo-Magi Demo")
    st.markdown(f"Provides users with domain specific information using Retrieval-Augmented Generation, including calculations and plots using NOAA's geomagnetic calculator API. More in-depth details can be found in the [AGU poster]({iposter_url})")
    
    if not st.user.is_logged_in:
        st.markdown("Please log in to access the chat interface. **Note: Only users with a 'colorado.edu' or 'noaa.gov' email address can access this demo.**")
        
        if st.button("Log in with Google"):
            st.login("google")
        return
    
    # email_domain = st.user.email.split("@")[1]
    # if email_domain not in ["colorado.edu", "noaa.gov"]:
    #     st.markdown("**Sorry, only users with a 'colorado.edu' or 'noaa.gov' email address can access this demo.**")
    #     if st.button("Log out"):
    #         st.logout()
    #     return
    
    with st.sidebar:
        st.info("⚠️ Feedback system is temporarily down!")
        st.markdown(
            """
            **Facing issues or noticing incorrect responses?** Please contact [mina7708@colorado.edu](mailto:mina7708@colorado.edu)
            """
        )

        st.markdown("---")
        st.markdown(f"Logged in as: {st.user.name}")

        if st.button("Log out"):
            st.logout()
            return
        
        if st.button("Clear Chat History"):
            st.session_state.chat_history = []
            st.session_state.message_counter = 0
            st.rerun()
    
    st.markdown("**Example prompts:** What is the magnetic declination in Boulder, CO? Could you make me a plot of the magnetic field strength in London from 1999 until now? What is magnetic inclination?")
    
    if "cgm_engine" not in st.session_state:
        with st.spinner("Initializing ChatGeo-Magi engine..."):
            try:
                llm, embeddings, retriever, cgm = setup_engine()
                cgm.initialize(llm, embeddings, retriever)
                st.session_state.cgm_engine = cgm
                st.success("Engine initialized successfully!")
            except Exception as e:
                st.error(f"Failed to initialize engine: {e}")
                st.stop()
    
    engine = st.session_state.cgm_engine
    
    for message in st.session_state.chat_history:
        display_chat_message(message, is_user=message.get("is_user", False))
    
    if prompt := st.chat_input("Ask me about geomagnetism..."):
        user_message = {"content": prompt, "is_user": True}
        st.session_state.chat_history.append(user_message)
        
        display_chat_message(user_message, is_user=True)
        
        with st.chat_message("assistant"):
            with st.spinner("Thinking..."):
                try:
                    thread_id = f"streamlit_session_{st.session_state.get('session_id', 'default')}"
                    response = engine.stream_invoke(prompt, thread_id=thread_id)
                    processed_response = process_agent_response(response)
                    st.session_state.chat_history.append(processed_response)
                    display_chat_message(processed_response, is_user=False)
                    
                except Exception as e:
                    error_message = {
                        "final_response": f"Sorry, I encountered an error: {str(e)}",
                        "agent_steps": [{
                            "step_type": "error",
                            "content": traceback.format_exc(),
                            "tool_calls": [],
                            "observations": [],
                            "reasoning": ""
                        }],
                        "plots": []
                    }
                    
                    st.session_state.chat_history.append(error_message)
                    display_chat_message(error_message, is_user=False)
                    
                    st.error("An error occurred while processing your request.")
                    with st.expander("Debug Information"):
                        st.text(traceback.format_exc())

def cleanup():
    """Clean up resources"""
    gc.collect()
    print("Cleaning up resources...")

if __name__ == "__main__":
    main()